### PR TITLE
Change release notes workflow to use release drafter

### PR DESCRIPTION
**Pull request by Sgitario**
Using release drafter which will keep the release draft version during the whole release. 
See an example of how it will look like: https://github.com/Sgitario/quarkus-catalog-apps/releases/tag/untagged-f343d00af00e9eb09536

### CODE REVIEW

**Comment by Sgitario** [comment]
@rsvoboda let me know if it looks ok for you now: https://github.com/Sgitario/quarkus-catalog-apps/releases/tag/untagged-f343d00af00e9eb09536
And thanks for letting me know about the release drafter action! It seems the official Github approach to do this.

**Comment by rsvoboda** [comment]
It gives me 404 :/ You probably need to add me as participant to your fork

**Comment by Sgitario** [comment]
> It gives me 404 :/ You probably need to add me as participant to your fork

Invitation sent. Let me know if you can see it now.

**Comment by rsvoboda** [comment]
I can see that now. Looks good!

**Review by rsvoboda — APPROVED** [review]

**Comment by rsvoboda** [comment]
Should I merge or do you want to wait for second eyes?

**Comment by Sgitario** [comment]
> Should I merge or do you want to wait for second eyes?

Merged. Draft release created: https://github.com/quarkus-qe/quarkus-catalog-apps/releases/tag/untagged-baf4040663fd5c812d1d

**Pull request merged**
